name: Keep Supabase active

on:
  workflow_dispatch:
  schedule:
    - cron: "17 2,10,18 * * *"

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Ping Supabase
        shell: bash
        run: |
          curl --fail --silent --show-error \
            --request POST \
            "https://khoztrzdfadovsgmfggi.supabase.co/rest/v1/rpc/kb2_get_initialization_status_v1" \
            --header "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtob3p0cnpkZmFkb3ZzZ21mZ2dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk4NDU0MTgsImV4cCI6MjA5NTQyMTQxOH0.72V5ZbvzHOk6k5XViVaEEB3Aoz9AjyLt3AGx5L3gqCY" \
            --header "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtob3p0cnpkZmFkb3ZzZ21mZ2dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk4NDU0MTgsImV4cCI6MjA5NTQyMTQxOH0.72V5ZbvzHOk6k5XViVaEEB3Aoz9AjyLt3AGx5L3gqCY" \
            --header "Content-Type: application/json" \
            --data "{}"

          echo ""
          echo "Supabase dang hoat dong."
